category: stegano
points:   100
name:     Для слепых
author:   nsychev
description: >
    <p>Даже слепой может читать между строк...</p>
urls:
    - "files/blind/task.pdf"
flags:
    - "ugra_preview"
