version: "3"
services:
    app:
        build: .
        image: ugractf/bow
        restart: always
        volumes:
            - ./public:/app
            - ./flag:/flag
        ports:
            - "5004:22"

