version: "2.2"
services:
    bin:
        build: .
        image: ugractf/oooverflow
        restart: always
        volumes:
            - ./app:/app
            - ./public:/app/public
        ports:
            - "5002:5000"
        cpus: "0.2"
        mem_limit: "128M"
        pids_limit: 30
