category: ppc
points:   250
name:     Print the input
author:   nsychev
description: >
    <p>Авторы задач по программированию думают, что тесты — это абсолютно секретная
    информация. Поэтому ваши программы они тестируют на разных странных строках:
    паролях, кодовых словах от своих банковских счетов, и даже на флагах!</p>
    <p><i>Флаг от этого задания расположен в одном из тестов к задаче
    «Print the input».</i></p>
    <p><i>Напоминаем, что систему Яндекс.Контест взламывать не надо.</i></p>
urls:
    - "https://contest.yandex.ru/contest/12894/problems/2"
flags:
    - "ugra_heck"

