category: pwn
points:   300
name:     Битва экстрасенсов
author:   nsychev
description: >
    <p>Иногда задачи бывают странные... Но на CTF-соревнованиях пригодятся все скиллы,
    в том числе и ясновидение.</p>
    <p>Поможет ли чекер угадать ответ с первой попытки?</p>
    <p><i>Флаг от этого задания будет доступен на странице «отчёт» после решения задачи
    «Битва экстрасенсов».</i></p>
    <p><i>Напоминаем, что систему Яндекс.Контест взламывать не надо.</i></p>
urls:
    - "https://contest.yandex.ru/contest/12894/problems/3"
    - "files/extrasense/check"
flags:
    - "ugra_peter_pwner_is_guesser"

